from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NAME = "unet"
_C.MODEL.NUM_CLASSES = 4

_C.DATASETS = CN()
_C.DATASETS.ROOT_PATH = "./data_split/ACDC"
_C.DATASETS.LABEL_NUM = 7
_C.DATASETS.MAX_SAMPLES = 80

_C.INPUT = CN()
_C.INPUT.PATCH_SIZE = [256, 256]

_C.SOLVER = CN()
_C.SOLVER.PRE_ITERATIONS = 10000
_C.SOLVER.MAX_ITERATIONS = 30000
_C.SOLVER.BATCH_SIZE = 24
_C.SOLVER.LABELED_BS = 12
_C.SOLVER.BASE_LR = 0.01
_C.SOLVER.PRE_MASK_RATIO = 0.25
_C.SOLVER.SELF_MASK_RATIO = 0.25
_C.SOLVER.EMA_ALPHA = 0.99
_C.SOLVER.VAL_INTERVAL = 500

_C.TEST = CN()
_C.TEST.STAGE_NAME = "self_train"

_C.EXP = "BCP"
_C.SEED = 1337
_C.DETERMINISTIC = 1
_C.GPU = 0
_C.PROCTITLE = "BCP_Train"
_C.OUTPUT_DIR = "./results"