MODEL:
  NAME: "unet"
  NUM_CLASSES: 2
DATASETS:
  ROOT_PATH: "./data_split/promise12"
  LABEL_NUM: 3
INPUT:
  PATCH_SIZE: [ 256, 256 ]
SOLVER:
  PRE_ITERATIONS: 10000
  MAX_ITERATIONS: 30000
  BATCH_SIZE: 24
  LABELED_BS: 12
  BASE_LR: 0.01
  PRE_MASK_RATIO: 0.25
  SELF_MASK_RATIO: 0.05
  VAL_INTERVAL: 200
  EMA_ALPHA: 0.99
TEST:
  STAGE_NAME: "self_train"
EXP: "BCP"
SEED: 1337
DETERMINISTIC: 1
GPU: 0
PROCTITLE: "Promise12"
OUTPUT_DIR: "./results"