MODEL:
  NAME: "unet"
  NUM_CLASSES: 4
DATASETS:
  ROOT_PATH: "./data_split/ACDC"
  LABEL_NUM: 3 # 3 7
INPUT:
  PATCH_SIZE: [ 256, 256 ]
SOLVER:
  PRE_ITERATIONS: 10000
  MAX_ITERATIONS: 30000
  BATCH_SIZE: 24
  LABELED_BS: 12
  BASE_LR: 0.01
  VAL_INTERVAL: 200
  PRE_MASK_RATIO: 0.25
  SELF_MASK_RATIO: 0.33
  EMA_ALPHA: 0.99
TEST:
  STAGE_NAME: "self_train"
EXP: "BCP"
SEED: 1337
DETERMINISTIC: 1
GPU: 0
PROCTITLE: "BCP_ACDC"
OUTPUT_DIR: "./results"