MODEL:
  NAME: "unet"
  NUM_CLASSES: 2 
DATASETS:
  ROOT_PATH: "./data_split/ISIC"
  LABEL_NUM: 55   # 3% 55  10% 183
INPUT:
  PATCH_SIZE: [224, 224]
SOLVER:
  PRE_ITERATIONS: 10000
  MAX_ITERATIONS: 30000
  BATCH_SIZE: 24
  LABELED_BS: 12
  BASE_LR: 0.01
  VAL_INTERVAL: 200
  PRE_MASK_RATIO: 0.5
  SELF_MASK_RATIO: 0.05
  EMA_ALPHA: 0.99
TEST:
  STAGE_NAME: "self_train"
EXP: "BCP"
SEED: 1337
DETERMINISTIC: 1
GPU: 0
PROCTITLE: "BCP_ISIC"
OUTPUT_DIR: "./results"