MODEL:
  NAME: "VNet"
  NUM_CLASSES: 2
DATASETS:
  ROOT_PATH: "./data_split/LA"
  LABEL_NUM: 4 # 4 8
  MAX_SAMPLES: 80
INPUT:
  PATCH_SIZE: [ 112, 112, 80 ]
SOLVER:
  PRE_ITERATIONS: 2000
  MAX_ITERATIONS: 15000
  BATCH_SIZE: 8
  LABELED_BS: 4
  BASE_LR: 0.01
  PRE_MASK_RATIO: 0.5
  SELF_MASK_RATIO: 0.05
  EMA_ALPHA: 0.99      
  VAL_INTERVAL: 200
TEST:
  STAGE_NAME: "self_train"
EXP: "BCP"
SEED: 1337
DETERMINISTIC: 1
GPU: 0
PROCTITLE: "BCP_LA"
OUTPUT_DIR: "./results"